"""initial

Revision ID: 66eb1dd9dca1
Revises: 
Create Date: 2025-11-05 13:43:46.911355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66eb1dd9dca1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('nama_anak', sa.String(length=100), nullable=False),
    sa.Column('nama_orang_tua', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('device_raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('berat_badan', sa.Float(), nullable=False),
    sa.Column('tinggi_badan', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_makanan', sa.String(length=255), nullable=False),
    sa.Column('usia_minimum', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('calon_ibu_prediction',
    sa.Column('id_prediction', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('usia', sa.Integer(), nullable=False),
    sa.Column('riwayat_gizi', sa.String(length=10), nullable=False),
    sa.Column('konsumsi_gizi', sa.String(length=10), nullable=False),
    sa.Column('cek_kesehatan', sa.String(length=10), nullable=False),
    sa.Column('riwayat_stunting', sa.String(length=10), nullable=False),
    sa.Column('pendidikan', sa.String(length=20), nullable=False),
    sa.Column('pola_asuh', sa.String(length=10), nullable=False),
    sa.Column('ekonomi', sa.String(length=20), nullable=False),
    sa.Column('tinggi_badan', sa.Float(), nullable=False),
    sa.Column('berat_badan', sa.Float(), nullable=False),
    sa.Column('hasil_prediksi', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_prediction')
    )
    op.create_table('stunting_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id_anak', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('nama_anak', sa.String(length=100), nullable=False),
    sa.Column('jenis_kelamin', sa.Integer(), nullable=False),
    sa.Column('umur', sa.Integer(), nullable=False),
    sa.Column('berat_badan', sa.Float(), nullable=False),
    sa.Column('tinggi_badan', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('hasil_prediksi', sa.String(length=20), nullable=False),
    sa.Column('tanggal_prediksi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_anak'], ['anak.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stunting_prediction')
    op.drop_table('calon_ibu_prediction')
    op.drop_table('user')
    op.drop_table('mpasi')
    op.drop_table('device_raw_data')
    op.drop_table('anak')
    # ### end Alembic commands ###
